name: Checks 

on: [push] 

jobs:
    test-lint:
      name: Test and Lint
      runs-on: ubuntu-20.04

      steps:
        - name: Login in to Docker Hub
          uses: docker/login-action@v1
          with: 
            username: ${{ secrets.DOCKERHUB_USER }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Check Out - pull repostirty code
          uses: actions/checkout@v2

        - name: Run Test-Code
        # 이때는 uses가 아닌, 모듈을 사용하는게 아니라 도커에 들어온 상태이고 코드에서 테스트를 하기위해 run.
          run: docker-compose run --rm app sh -c 'python manage.py wait_for_db && python manage.py test'

        - name: Run Flake8 for Linting # pep8 style guide를 잘 준수하고 있는지 체크
          run: docker-compose run --rm app sh -c 'flake8'
          